ElynnaChuang/twitter-api-2020

Procfile, app.js, config/config.json
=> heroku init

controllers/tweet-controller.js, routes/index.js
=> feat: add get tweets function

controllers/user-controller.js, package-lock.json
新增 isFollowing 資料在回傳中，讓前端判斷登入的使用者有沒有追蹤
=> fix: add isFollowing parameter in get user

controllers/user-controller.js, routes/index.js
=> feat: get user's tweets

controllers/admin-controller.js, routes/index.js
=> feat: add admin get users

controllers/tweet-controller.js
=> fix: add number of replies and likes to getTweets or getTweet

controllers/user-controller.js, routes/index.js
=> feat: get user's likes

controllers/user-controller.js, routes/index.js
=> feat: get user's followers

controllers/user-controller.js, routes/index.js
先不要合（可先review）
這隻是取得某位user追蹤中的人
=> feat: get user's followings

controllers/user-controller.js, routes/index.js
取得推薦追蹤的使用者
@peggy8865  如果沒問題可以合
=> feat: get recommend users

controllers/reply-controller.js, controllers/tweet-controller.js
補 isLike 到推文回傳值
postReply 我加上"使用者不存在"囉
=> fix: add isLike on tweets and modify postReply

controllers/admin-controller.js
=> fix: use raw queries to get users

controllers/reply-controller.js, routes/index.js
=> feat: add get replies function

controllers/admin-controller.js, routes/index.js
=> feat: admin delete a tweet

controllers/followship-controller.js, routes/index.js
=> feat: add followships

controllers/user-controller.js
=> fix: edit user profile

controllers/followship-controller.js, routes/index.js
=> feat: remove followships

seeders/20230316091810-user-seed-file.js
=> fix: user seeder

controllers/user-controller.js
=> fix: add tweets nums in get user

controllers/user-controller.js
=> fix: add id in user's replied tweets

controllers/user-controller.js
1. 更正 isFollowing 寫法，問號應加在 signinUser.Followings 後。
2. 改變 getUserFollowers 和 getUserFollowings 查詢語法，以避免 travis 測試出現 query run error。
=> fix: modify isFollowing when get user followships

controllers/user-controller.js
=> fix: error

controllers/reply-controller.js
=> fix: modify syntax in replyController

controllers/admin-controller.js
=> fix: modify syntax in adminController

controllers/tweet-controller.js
=> fix: if user does not exist when posting tweet

controllers/tweet-controller.js, controllers/user-controller.js
=> fix: add followships order by createdAt
